/**
 * Deal Tracker Seed Data
 *
 * All 5 phases, ~50 tasks, and subtasks for the 120-Day ESOP Transaction Roadmap.
 * Used to initialize a new client's tracker.
 */

export interface SeedSubtask {
	id: string;
	label: string;
}

export interface SeedTask {
	id: string;
	phase: "ignition" | "build" | "validate" | "close-prep" | "closing";
	day: string;
	dayNumber: number;
	role: string;
	type: "milestone" | "action" | "deadline" | "deliverable" | "gate";
	title: string;
	subs: string[];
	order: number;
}

export interface SeedGate {
	id: string;
	day: string;
	dayNumber: number;
	name: string;
	phase: string;
}

// ─── Gate Data ──────────────────────────────────────────────────

export const SEED_GATES: SeedGate[] = [
	{
		id: "g1",
		day: "Day 45",
		dayNumber: 45,
		name: "FMV adequacy letter",
		phase: "Phase 2",
	},
	{
		id: "g2",
		day: "Day 60",
		dayNumber: 60,
		name: "Lender commitment letter",
		phase: "Phase 3",
	},
	{
		id: "g3",
		day: "Day 75",
		dayNumber: 75,
		name: "QofE EBITDA validation",
		phase: "Phase 3",
	},
	{
		id: "g4",
		day: "Day 90",
		dayNumber: 90,
		name: "Trustee COOP sign-off",
		phase: "Phase 4",
	},
];

// ─── Task Data ──────────────────────────────────────────────────

export const SEED_TASKS: SeedTask[] = [
	// Phase 1 — Ignition (Days 1–14)
	{
		id: "t1_1",
		phase: "ignition",
		day: "D.1",
		dayNumber: 1,
		role: "Owner/Seller",
		type: "milestone",
		order: 1,
		title: "$25,000 non-refundable retainer wire received",
		subs: [
			"Wire initiated from company operating account",
			"Forhemit confirms receipt and issues engagement confirmation",
			"Deal file opened in CRM with retainer date as Day 1",
			"Broker notified of engagement activation",
			"COOP intake clock starts immediately",
		],
	},
	{
		id: "t1_2",
		phase: "ignition",
		day: "D.1",
		dayNumber: 1,
		role: "Owner/Seller",
		type: "action",
		order: 2,
		title: "S-corp vs. C-corp decision initiated",
		subs: [
			"Seller confirms current entity structure",
			"If S-corp: CPA engaged for built-in gains tax analysis",
			"BIG analysis covers 5-year recognition period",
			"CPA calculates net tax impact vs. §1042 benefit",
			"Conversion timeline confirmed",
			"ERISA counsel notified of entity structure",
		],
	},
	{
		id: "t1_3",
		phase: "ignition",
		day: "D.1",
		dayNumber: 1,
		role: "Owner/Seller",
		type: "action",
		order: 3,
		title: "ERISA workforce eligibility confirmed",
		subs: [
			"Full W-2 employee roster obtained",
			"Non-citizens/non-permanent-residents flagged",
			"Visa-status employees identified",
			"Minimum 20 eligible employees confirmed",
			"Eligibility data delivered to ERISA counsel",
		],
	},
	{
		id: "t1_4",
		phase: "ignition",
		day: "D.1",
		dayNumber: 1,
		role: "Broker",
		type: "action",
		order: 4,
		title: "Listing agreement confirmed to cover ESOP",
		subs: [
			"Broker reviews listing for buyer-type restrictions",
			"Commission rate confirmed applicable for ESOP",
			"Any ambiguity resolved in writing before LOI",
			"Exclusivity terms reviewed for ESOP compatibility",
		],
	},
	{
		id: "t1_5",
		phase: "ignition",
		day: "D.1",
		dayNumber: 1,
		role: "Forhemit",
		type: "milestone",
		order: 5,
		title: "COOP intake launched — all four tracks",
		subs: [
			"Track 1 (People): key person identification",
			"Track 2 (Systems): technology stack documented",
			"Track 3 (Financial): accounting systems, bank access",
			"Track 4 (Governance): board structure, corporate records",
			"COOP intake forms distributed",
			"Initial findings flagged within 72 hours",
		],
	},
	{
		id: "t1_6",
		phase: "ignition",
		day: "D.3",
		dayNumber: 3,
		role: "Forhemit",
		type: "deadline",
		order: 6,
		title: "QofE firm engaged",
		subs: [
			"QofE firm selected with industry experience",
			"Engagement letter executed",
			"QofE firm receives preliminary financial data",
			"Revenue recognition methodology confirmed",
			"Owner compensation normalization scope defined",
			"QofE timeline confirmed: field work Day 15, report Day 42",
		],
	},
	{
		id: "t1_7",
		phase: "ignition",
		day: "D.7",
		dayNumber: 7,
		role: "Forhemit",
		type: "deadline",
		order: 7,
		title: "Independent ESOP trustee retained",
		subs: [
			"Trustee shortlist reviewed",
			"Conflict check completed",
			"Experience at target deal size confirmed",
			"Engagement letter executed",
			"Trustee fees quoted and disclosed",
			"ERISA counsel approves selection",
		],
	},
	{
		id: "t1_8",
		phase: "ignition",
		day: "D.7",
		dayNumber: 7,
		role: "Forhemit",
		type: "deadline",
		order: 8,
		title: "ESOP/ERISA counsel engaged",
		subs: [
			"Conflict check completed",
			"ESOP experience at target deal size confirmed",
			"Engagement letter executed",
			"Plan design session scheduled for Week 2",
			"Independence matrix reviewed",
		],
	},
	{
		id: "t1_9",
		phase: "ignition",
		day: "D.7",
		dayNumber: 7,
		role: "Lender",
		type: "deadline",
		order: 9,
		title: "Lender credit pre-screen complete",
		subs: [
			"Lender confirms ESOP-specific ESOP lending experience",
			"Credit fit memo delivered",
			"PLP authority confirmed",
			"Dual-lender identified if deal >$5M",
			"Preliminary rate and term provided",
		],
	},
	{
		id: "t1_10",
		phase: "ignition",
		day: "D.10",
		dayNumber: 10,
		role: "Owner/Seller",
		type: "deliverable",
		order: 10,
		title: "Data room populated — financial package",
		subs: [
			"Last 3 years business tax returns",
			"Year-end financials — 3 years",
			"Current YTD P&L/BS/CF",
			"A/R and A/P aging",
			"Customer concentration analysis",
			"Outstanding litigation disclosed",
			"Owner compensation detail",
		],
	},
	{
		id: "t1_11",
		phase: "ignition",
		day: "D.14",
		dayNumber: 14,
		role: "Forhemit",
		type: "deliverable",
		order: 11,
		title: "COOP v1.0 baseline assessment delivered",
		subs: [
			"Key person dependency map",
			"Critical vendor list",
			"Technology stack documentation",
			"Customer relationship map",
			"Financial system access",
			"Immediate risk flags identified",
			"COOP v1.0 delivered to trustee and lender",
		],
	},
	{
		id: "t1_12",
		phase: "ignition",
		day: "D.14",
		dayNumber: 14,
		role: "Broker",
		type: "milestone",
		order: 12,
		title: "Pre-COOP status document issued",
		subs: [
			"Broker receives written confirmation",
			"Status document includes team roster and milestones",
			"Broker uses to manage seller expectations",
			"Next check-in scheduled (Day 28)",
		],
	},

	// Phase 2 — Build (Days 15–45)
	{
		id: "t2_1",
		phase: "build",
		day: "D.15",
		dayNumber: 15,
		role: "CPA",
		type: "action",
		order: 1,
		title: "QofE field work begins",
		subs: [
			"On-site or remote financial review launched",
			"Owner compensation add-backs documented",
			"One-time expenses identified and separated",
			"Revenue recognition reviewed",
			"Customer concentration risk quantified",
			"Preliminary adjusted EBITDA by Day 20",
		],
	},
	{
		id: "t2_2",
		phase: "build",
		day: "D.18",
		dayNumber: 18,
		role: "Owner/Seller",
		type: "deliverable",
		order: 2,
		title: "Data room populated — operational package",
		subs: [
			"Employee roster with tenure and compensation",
			"Vendor contracts with change-of-control provisions",
			"Lease agreements with renewal options",
			"Equipment inventory",
			"Insurance policies",
			"Customer contracts with renewal dates",
			"Regulatory licenses and permits",
		],
	},
	{
		id: "t2_3",
		phase: "build",
		day: "D.20",
		dayNumber: 20,
		role: "Forhemit",
		type: "deliverable",
		order: 3,
		title: "COOP v2.0 — operational map delivered",
		subs: [
			"Key person succession gaps with mitigation plans",
			"Customer relationship continuity assessed",
			"Technology access verified",
			"Vendor contracts reviewed for change-of-control",
			"Financial system access map updated",
			"COOP v2.0 delivered to lender and trustee",
		],
	},
	{
		id: "t2_4",
		phase: "build",
		day: "D.21",
		dayNumber: 21,
		role: "Lender",
		type: "action",
		order: 4,
		title: "Lender site visit (if required)",
		subs: [
			"Forhemit coordinates scheduling",
			"COOP v1.0 provided as site visit prep",
			"Lender meets key management team",
			"Physical assets inspected",
			"Any concerns documented and addressed",
		],
	},
	{
		id: "t2_5",
		phase: "build",
		day: "D.25",
		dayNumber: 25,
		role: "Forhemit",
		type: "deliverable",
		order: 5,
		title: "Draft LOI structure — capital stack design",
		subs: [
			"senior lender debt calculated",
			"Dual-lender stack confirmed if >$5M",
			"Seller note terms proposed",
			"Refinance trigger at Month 14–18 documented",
			"Cash at close estimate calculated",
			"Capital stack submitted for review",
		],
	},
	{
		id: "t2_6",
		phase: "build",
		day: "D.28",
		dayNumber: 28,
		role: "Broker",
		type: "action",
		order: 6,
		title: "LOI terms reviewed with seller and counsel",
		subs: [
			"Purchase price and cash at close explained",
			"Refinance trigger mechanics explained",
			"§1042 election implications explained",
			"Seller's attorney reviews draft LOI",
			"Seller's CPA reviews tax implications",
			"Any concerns addressed before execution",
		],
	},
	{
		id: "t2_7",
		phase: "build",
		day: "D.30",
		dayNumber: 30,
		role: "Lender",
		type: "deadline",
		order: 7,
		title: "Complete lender package submitted",
		subs: [
			"QofE preliminary findings included",
			"COOP v2.0 included",
			"Capital stack proposal included",
			"Management projections included",
			"Collateral analysis included",
			"Seller note subordination terms submitted",
		],
	},
	{
		id: "t2_8",
		phase: "build",
		day: "D.35",
		dayNumber: 35,
		role: "Trustee",
		type: "deadline",
		order: 8,
		title: "FMV appraisal delivered to trustee",
		subs: [
			"Independent ERISA FMV appraisal delivered",
			"Appraiser engaged by trustee",
			"Appraisal methodology documented",
			"Concluded value compared to purchase price",
			"Trustee reviews methodology and assumptions",
		],
	},
	{
		id: "t2_9",
		phase: "build",
		day: "D.40",
		dayNumber: 40,
		role: "Forhemit",
		type: "deliverable",
		order: 9,
		title: "COOP v3.0 — validated",
		subs: [
			"QofE findings incorporated",
			"Lender feedback incorporated",
			"Financial projections validated against EBITDA",
			"Debt service coverage confirmed",
			"Operational readiness score assigned",
			"COOP v3.0 delivered to trustee and lender",
		],
	},
	{
		id: "t2_10",
		phase: "build",
		day: "D.42",
		dayNumber: 42,
		role: "CPA",
		type: "deadline",
		order: 10,
		title: "QofE report delivered — final adjusted EBITDA",
		subs: [
			"Final adjusted EBITDA confirmed",
			"Normalized owner compensation calculated",
			"One-time items separated from run-rate",
			"Customer concentration risk disclosed",
			"QofE delivered to all parties simultaneously",
			"Within 15% of LOI assumption?",
		],
	},
	{
		id: "t2_gate",
		phase: "build",
		day: "D.45",
		dayNumber: 45,
		role: "Trustee",
		type: "gate",
		order: 11,
		title: "GATE 1 — FMV adequacy letter",
		subs: [
			"Trustee confirms purchase price is fair under ERISA",
			"FMV adequacy letter issued in writing",
			"If FMV below target: gap quantified",
			"If seller refuses adjustment: process stops",
			"If cleared: LOI drafting begins immediately",
		],
	},

	// Phase 3 — Validate (Days 46–75)
	{
		id: "t3_1",
		phase: "validate",
		day: "D.46",
		dayNumber: 46,
		role: "All Parties",
		type: "milestone",
		order: 1,
		title: "LOI executed",
		subs: [
			"LOI signed by seller and ESOP trustee",
			"Purchase price confirmed with FMV letter",
			"Capital stack structure confirmed",
			"Exclusivity period begins",
			"Broker commission terms confirmed in writing",
		],
	},
	{
		id: "t3_2",
		phase: "validate",
		day: "D.48",
		dayNumber: 48,
		role: "Legal",
		type: "action",
		order: 2,
		title: "ESOP plan document drafting begins",
		subs: [
			"ESOP plan document drafted",
			"Trust agreement drafted",
			"Board resolutions drafted",
			"Allocation formula selected",
			"Vesting schedule finalized",
			"Eligibility rules confirmed",
		],
	},
	{
		id: "t3_3",
		phase: "validate",
		day: "D.50",
		dayNumber: 50,
		role: "Lender",
		type: "deadline",
		order: 3,
		title: "Final underwriting submission",
		subs: [
			"Executed LOI included",
			"Final QofE report included",
			"COOP v3.0 included",
			"Management projections included",
			"Seller note subordination draft included",
			"Collateral schedule finalized",
		],
	},
	{
		id: "t3_4",
		phase: "validate",
		day: "D.52",
		dayNumber: 52,
		role: "Owner/Seller",
		type: "action",
		order: 4,
		title: "Key employee retention plan finalized",
		subs: [
			"Key employees identified from COOP",
			"Retention arrangements documented",
			"Stay bonuses or ESOP participation terms set",
			"Employment terms reviewed",
		],
	},
	{
		id: "t3_5",
		phase: "validate",
		day: "D.55",
		dayNumber: 55,
		role: "Owner/Seller",
		type: "action",
		order: 5,
		title: "Post-close employment agreement negotiation",
		subs: [
			"Duration of employment or consulting defined",
			"Compensation terms set",
			"Non-compete provisions reviewed",
			"Transition responsibilities documented",
		],
	},
	{
		id: "t3_6",
		phase: "validate",
		day: "D.56",
		dayNumber: 56,
		role: "Forhemit",
		type: "deliverable",
		order: 6,
		title: "Seller note and subordination — draft",
		subs: [
			"Seller note terms finalized",
			"Mandatory refinance trigger at Month 14–18",
			"Subordination to lender debt confirmed",
			"Triparty document drafted",
		],
	},
	{
		id: "t3_gate2",
		phase: "validate",
		day: "D.60",
		dayNumber: 60,
		role: "Lender",
		type: "gate",
		order: 7,
		title: "GATE 2 — Lender commitment letter",
		subs: [
			"Formal commitment letter issued",
			"Senior debt amount confirmed",
			"Interest rate and term defined",
			"If not issued by Day 65: lender replaced or timeline extends",
		],
	},
	{
		id: "t3_7",
		phase: "validate",
		day: "D.62",
		dayNumber: 62,
		role: "Legal",
		type: "action",
		order: 8,
		title: "Purchase agreement drafting begins",
		subs: [
			"PSA drafted by ERISA counsel",
			"Seller's counsel receives draft",
			"Representations and warranties negotiated",
			"Indemnification provisions reviewed",
		],
	},
	{
		id: "t3_8",
		phase: "validate",
		day: "D.65",
		dayNumber: 65,
		role: "Broker",
		type: "action",
		order: 9,
		title: "Seller note terms reviewed with seller",
		subs: [
			"Refinance trigger mechanics explained",
			"Month 14–18 paydown conditions clarified",
			"Seller CPA and attorney review complete",
		],
	},
	{
		id: "t3_9",
		phase: "validate",
		day: "D.68",
		dayNumber: 68,
		role: "Forhemit",
		type: "action",
		order: 10,
		title: "Lease and vendor change-of-control review",
		subs: [
			"All leases reviewed for change-of-control",
			"Key vendor contracts reviewed",
			"Required consents identified",
			"Landlord consent process initiated",
		],
	},
	{
		id: "t3_10",
		phase: "validate",
		day: "D.70",
		dayNumber: 70,
		role: "Forhemit",
		type: "deliverable",
		order: 11,
		title: "COOP v3.5 — lender covenants integrated",
		subs: [
			"Lender covenants incorporated",
			"Debt service coverage requirements added",
			"Reporting obligations documented",
			"CapEx reserve requirements added",
		],
	},
	{
		id: "t3_gate3",
		phase: "validate",
		day: "D.75",
		dayNumber: 75,
		role: "CPA",
		type: "gate",
		order: 12,
		title: "GATE 3 — QofE EBITDA validation",
		subs: [
			"Adjusted EBITDA within 15% of LOI assumption",
			"If outside band: process stops",
			"Purchase price renegotiated if needed",
			"Capital stack restructured before drafting",
		],
	},

	// Phase 4 — Close Prep (Days 76–105)
	{
		id: "t4_1",
		phase: "close-prep",
		day: "D.78",
		dayNumber: 78,
		role: "Legal",
		type: "action",
		order: 1,
		title: "PSA — second draft with seller counsel edits",
		subs: [
			"Seller's counsel returns redline",
			"Representations and indemnification negotiated",
			"Survival periods reviewed",
			"No conflict with ESOP plan terms",
		],
	},
	{
		id: "t4_2",
		phase: "close-prep",
		day: "D.80",
		dayNumber: 80,
		role: "Broker",
		type: "action",
		order: 2,
		title: "Seller note and subordination — final review",
		subs: [
			"Seller note terms finalized for execution",
			"Subordination structure reviewed",
			"Refinance trigger mechanics confirmed",
			"§1042 reinvestment requirements reviewed",
		],
	},
	{
		id: "t4_3",
		phase: "close-prep",
		day: "D.82",
		dayNumber: 82,
		role: "Owner/Seller",
		type: "deadline",
		order: 3,
		title: "Employment or transition agreement executed",
		subs: [
			"Post-close terms signed",
			"Non-compete provisions enforceable",
			"Transition responsibilities with milestones",
			"Knowledge transfer checkpoints defined",
		],
	},
	{
		id: "t4_4",
		phase: "close-prep",
		day: "D.83",
		dayNumber: 83,
		role: "Forhemit",
		type: "deadline",
		order: 4,
		title: "Landlord and vendor consents obtained",
		subs: [
			"All change-of-control consents in hand",
			"Landlord consent escalated if outstanding",
			"Vendor consents documented",
		],
	},
	{
		id: "t4_5",
		phase: "close-prep",
		day: "D.85",
		dayNumber: 85,
		role: "Lender",
		type: "action",
		order: 5,
		title: "Lender loan documents distributed",
		subs: [
			"Complete lender loan package distributed",
			"Note, security agreement, guaranty included",
			"All parties have 10 days to review",
		],
	},
	{
		id: "t4_6",
		phase: "close-prep",
		day: "D.85",
		dayNumber: 85,
		role: "Forhemit",
		type: "deliverable",
		order: 6,
		title: "Employee communication plan finalized",
		subs: [
			"ESOP announcement plan drafted",
			"Message comes from owner, not Forhemit",
			"Communication timeline set",
			"Talking points and FAQ prepared",
		],
	},
	{
		id: "t4_7",
		phase: "close-prep",
		day: "D.88",
		dayNumber: 88,
		role: "Forhemit",
		type: "deliverable",
		order: 7,
		title: "COOP v4.0 — final (pre-trustee review)",
		subs: [
			"All four COOP tracks finalized",
			"Key person succession verified",
			"Technology access documented",
			"Vendor relationships transitioned",
			"Customer continuity plan in place",
			"Submitted to trustee for Gate 4 review",
		],
	},
	{
		id: "t4_gate4",
		phase: "close-prep",
		day: "D.90",
		dayNumber: 90,
		role: "Trustee",
		type: "gate",
		order: 8,
		title: "GATE 4 — Trustee COOP sign-off",
		subs: [
			"Trustee formally accepts COOP",
			"Business confirmed operationally viable post-close",
			"If conditions issued: Forhemit addresses each",
			"If accepted: closing date scheduled Days 115–120",
		],
	},
	{
		id: "t4_8",
		phase: "close-prep",
		day: "D.95",
		dayNumber: 95,
		role: "Legal",
		type: "deadline",
		order: 9,
		title: "All closing documents in final form",
		subs: [
			"PSA in executable form",
			"ESOP plan document final",
			"Trust agreement final",
			"Seller note final",
			"Lender loan documents final",
			"Trustee counsel conducts final review",
		],
	},
	{
		id: "t4_9",
		phase: "close-prep",
		day: "D.100",
		dayNumber: 100,
		role: "Owner/Seller",
		type: "deadline",
		order: 10,
		title: "Board resolution — approve ESOP and transaction",
		subs: [
			"Board formally authorizes ESOP plan",
			"Trustee engagement authorized",
			"Sale of stock to ESOP trust authorized",
			"ERISA counsel provides resolution template",
		],
	},
	{
		id: "t4_10",
		phase: "close-prep",
		day: "D.100",
		dayNumber: 100,
		role: "Forhemit",
		type: "deliverable",
		order: 11,
		title: "§1042 election package prepared",
		subs: [
			"QRP strategy confirmed with wealth advisor",
			"Seller CPA calculates actual basis",
			"§1042 benefit confirmed vs. marketing assumptions",
		],
	},
	{
		id: "t4_11",
		phase: "close-prep",
		day: "D.105",
		dayNumber: 105,
		role: "Broker",
		type: "action",
		order: 12,
		title: "Pre-closing checklist — confirm with seller",
		subs: [
			"Wire instructions confirmed by phone",
			"§1042 election understood",
			"Employment agreement signed",
			"Board resolution adopted",
			"CPA has final closing cost estimate",
		],
	},

	// Phase 5 — Closing (Days 106–120)
	{
		id: "t5_1",
		phase: "closing",
		day: "D.106",
		dayNumber: 106,
		role: "Legal",
		type: "deadline",
		order: 1,
		title: "Title and lien search complete",
		subs: [
			"Final verification of no undisclosed liens",
			"No encumbrances or claims against assets",
			"Any issues resolved before closing date",
		],
	},
	{
		id: "t5_2",
		phase: "closing",
		day: "D.108",
		dayNumber: 108,
		role: "All Parties",
		type: "action",
		order: 2,
		title: "Wire fraud protocol — phone verification",
		subs: [
			"Every wire destination phone-verified",
			"Email confirmation alone is insufficient",
			"Wire fraud targeting M&A closings is active",
			"This step is non-negotiable",
		],
	},
	{
		id: "t5_3",
		phase: "closing",
		day: "D.110",
		dayNumber: 110,
		role: "Lender",
		type: "deadline",
		order: 3,
		title: "Lender authorization and funding instructions",
		subs: [
			"Lender authorization confirmed",
			"Funding instructions distributed to closing agent",
			"Final lender conditions resolved",
			"Funding date confirmed",
		],
	},
	{
		id: "t5_4",
		phase: "closing",
		day: "D.112",
		dayNumber: 112,
		role: "Forhemit",
		type: "deliverable",
		order: 4,
		title: "Day 121 readiness confirmation to trustee",
		subs: [
			"Written confirmation to trustee",
			"Post-close management team briefed",
			"All four COOP tracks confirmed green",
			"Closing date confirmed to all parties",
		],
	},
	{
		id: "t5_5",
		phase: "closing",
		day: "D.114",
		dayNumber: 114,
		role: "Owner/Seller",
		type: "milestone",
		order: 5,
		title: "Employee announcement delivered by owner",
		subs: [
			"Owner delivers ESOP announcement in person",
			"Forhemit communication framework used",
			"Message: employees are now owners",
			"Forhemit stays behind the scenes",
		],
	},
	{
		id: "t5_6",
		phase: "closing",
		day: "D.115",
		dayNumber: 115,
		role: "Legal",
		type: "action",
		order: 6,
		title: "Pre-closing document distribution",
		subs: [
			"Complete closing binder distributed",
			"All documents in executable form",
			"Signature blocks flagged",
			"Closing logistics confirmed",
		],
	},
	{
		id: "t5_7",
		phase: "closing",
		day: "D.120",
		dayNumber: 120,
		role: "All Parties",
		type: "milestone",
		order: 7,
		title: "CLOSING DAY — documents executed",
		subs: [
			"PSA signed by seller and trustee",
			"Lender loan documents executed",
			"ESOP plan formally adopted",
			"Employment agreement in effect",
			"Seller note executed",
			"Trustee takes title to shares",
			"Every eligible employee is now an owner",
		],
	},
	{
		id: "t5_8",
		phase: "closing",
		day: "D.120",
		dayNumber: 120,
		role: "Broker",
		type: "milestone",
		order: 8,
		title: "Commission paid from proceeds",
		subs: [
			"Broker commission wired from lender proceeds",
			"Forhemit structuring fee wired",
			"Seller receives net cash at close",
			"Seller note established per schedule",
			"Closing confirmation in writing",
		],
	},
	{
		id: "t5_9",
		phase: "closing",
		day: "D.120+",
		dayNumber: 121,
		role: "Forhemit",
		type: "deliverable",
		order: 9,
		title: "Post-close stewardship begins — Day 121",
		subs: [
			"Operational stewardship launches: 12–24 months",
			"Early-warning monitoring active",
			"Quarterly reporting to trustee",
			"Annual ESOP compliance coordination",
			"Month 14–18 refinance trigger monitored",
		],
	},
];

// ─── Gate Status Map ────────────────────────────────────────────

export const GATE_STATUS_MAP: Record<
	string,
	{ gateId: string; taskId: string }
> = {
	gate1: { gateId: "g1", taskId: "t2_gate" },
	gate2: { gateId: "g2", taskId: "t3_gate2" },
	gate3: { gateId: "g3", taskId: "t3_gate3" },
	gate4: { gateId: "g4", taskId: "t4_gate4" },
};

// ─── Phase Map ──────────────────────────────────────────────────

export const PHASE_MAP = {
	ignition: { name: "Phase 1 — Ignition", days: "Days 1–14", color: "#185FA5" },
	build: { name: "Phase 2 — Build", days: "Days 15–45", color: "#3B6D11" },
	validate: {
		name: "Phase 3 — Validate",
		days: "Days 46–75",
		color: "#854F0B",
	},
	"close-prep": {
		name: "Phase 4 — Close Prep",
		days: "Days 76–105",
		color: "#D4763A",
	},
	closing: {
		name: "Phase 5 — Closing",
		days: "Days 106–120",
		color: "#A32D2D",
	},
} as const;
