/**
 * CRM — shared data layer
 *
 * Types, constants, and utilities for the CRM feature.
 * Hooks stay in apps (Convex-dependent).
 */

// Types (legacy — kept during migration)
export type {
	PipelineStage,
	NdaStatus,
	ActivityType,
	CrmView,
	TaskPriority,
	TaskStatus,
	SortDirection,
	SortField,
	SortConfig,
	DueFilter,
	StageStyle,
	Company,
	Contact,
	Activity,
	Task,
	CompanyFilters,
	PipelineStats,
	CompanyFormData,
	ContactFormData,
	ActivityFormData,
	TaskFormData,
} from "./types";

export {
	PIPELINE_STAGES,
	NDA_STATUS,
	ACTIVITY_TYPES,
	CRM_VIEWS,
	TASK_PRIORITIES,
	TASK_STATUSES,
	STAGE_STYLES,
} from "./types";

// ── Stewardship CRM Constants & Types ────────────────────────────────────────
// New relationship/nurture-focused constants. Phase 1 of CRM refocus.
export type {
	DealStage,
	TerminalStage,
	ActiveStage,
	ContactType,
	AdvisorType,
	FinancialRange,
	EmployeeRange,
	TransitionTimeline,
	PrimaryMotivation,
	NurtureStage,
	RelationshipStage,
	InteractionType,
	SentimentValue,
	ContactFrequency,
	UrgencyLevel,
	TrustLevel,
	BusinessModel,
	IndustryCategory,
	CloseConfidence,
	Profitability,
	GrowthTrend,
	OwnerDependency,
	IdentityAttachment,
	OpennessLevel,
	SuccessorOption,
	AdvisorOpenness,
	RelationshipStrength,
	PreferredContactMethod,
	HowWeHeard,
	AssetType,
	NextNurtureAction,
	CrmDocumentType,
} from "./stewardship-constants";

export {
	DEAL_STAGES,
	TERMINAL_STAGES,
	ACTIVE_STAGES,
	CONTACT_TYPES,
	ADVISOR_TYPES,
	FINANCIAL_RANGES,
	EMPLOYEE_RANGES,
	TRANSITION_TIMELINES,
	PRIMARY_MOTIVATIONS,
	NURTURE_STAGES,
	RELATIONSHIP_STAGES,
	INTERACTION_TYPES,
	SENTIMENT_VALUES,
	CONTACT_FREQUENCIES,
	URGENCY_LEVELS,
	TRUST_LEVELS,
	BUSINESS_MODELS,
	INDUSTRY_CATEGORIES,
	CLOSE_CONFIDENCE_VALUES,
	PROFITABILITY_LEVELS,
	GROWTH_TRENDS,
	OWNER_DEPENDENCY_LEVELS,
	IDENTITY_ATTACHMENT_LEVELS,
	OPENNESS_LEVELS,
	SUCCESSOR_OPTIONS,
	ADVISOR_OPENNESS,
	RELATIONSHIP_STRENGTHS,
	PREFERRED_CONTACT_METHODS,
	HOW_WE_HEARD_OPTIONS,
	ASSET_TYPES,
	NEXT_NURTURE_ACTIONS,
	CRM_DOCUMENT_TYPES,
	STAGE_MIGRATION_MAP,
	DEAL_STAGE_STYLES,
	DEAL_STAGE_OPTIONS,
	CONTACT_TYPE_OPTIONS,
	ADVISOR_TYPE_OPTIONS,
	FINANCIAL_RANGE_OPTIONS,
	EMPLOYEE_RANGE_OPTIONS,
	TRANSITION_TIMELINE_OPTIONS,
	PRIMARY_MOTIVATION_OPTIONS,
	NURTURE_STAGE_OPTIONS,
	RELATIONSHIP_STAGE_OPTIONS,
	INTERACTION_TYPE_OPTIONS,
	SENTIMENT_OPTIONS,
	CONTACT_FREQUENCY_OPTIONS,
	URGENCY_OPTIONS,
	TRUST_LEVEL_OPTIONS,
	BUSINESS_MODEL_OPTIONS,
	INDUSTRY_OPTIONS,
	CLOSE_CONFIDENCE_OPTIONS,
	PROFITABILITY_OPTIONS,
	GROWTH_TREND_OPTIONS,
	OWNER_DEPENDENCY_OPTIONS,
	SUCCESSOR_OPTIONS_LIST,
	NEXT_NURTURE_ACTION_OPTIONS,
	HOW_WE_HEARD_OPTIONS_LIST,
	ASSET_TYPE_OPTIONS,
	PREFERRED_CONTACT_OPTIONS,
	CRM_DOCUMENT_TYPE_OPTIONS,
	IDENTITY_ATTACHMENT_OPTIONS,
	OPENNESS_OPTIONS,
	ADVISOR_OPENNESS_OPTIONS,
	RELATIONSHIP_STRENGTH_OPTIONS,
} from "./stewardship-constants";

export type { StageStyle as StewardshipStageStyle } from "./stewardship-constants";

// ── Stewardship CRM Types ────────────────────────────────────────────────────
export type {
	CompanyV2,
	ContactV2,
	InteractionV2,
	CrmDocumentV2,
	CompanyFees,
	CompanyGates,
	FeeMilestone,
	CompanyFormDataV2,
	OwnerFormData,
	BrokerFormData,
	AdvisorFormData,
	ContactFormDataV2,
	InteractionFormDataV2,
	DocumentFormDataV2,
	CompanyFiltersV2,
	PipelineStatsV2,
	ContactFiltersV2,
	InteractionFiltersV2,
	SortDirectionV2,
	CompanySortField,
	SortConfigV2,
	CrmViewV2,
	CompanyV1,
	ContactV1,
	ActivityV1,
	TaskV1,
	CompanyFormDataV1,
	ContactFormDataV1,
	CompanyFiltersV1,
	PipelineStatsV1,
} from "./stewardship-types";

export { CRM_VIEWS_V2 } from "./stewardship-types";

// Constants
export {
	DEFAULT_COMPANY_VALUES,
	DEFAULT_ACTIVITY_VALUES,
	DEFAULT_TASK_VALUES,
	STAGE_OPTIONS,
	NDA_OPTIONS,
	ACTIVITY_TYPE_OPTIONS,
	PRIORITY_OPTIONS,
	SORT_OPTIONS,
	FILTER_LABELS,
	DEFAULT_PAGE_SIZE,
	DAYS_OF_WEEK,
	MONTHS,
	COMMON_INDUSTRIES,
	COMMON_ADVISORS,
} from "./constants";

// Formatters
export {
	formatDate,
	getRelativeDate,
	daysUntil,
	getTodayString,
	getDateOffset,
	getStageStyle,
	getNdaBadgeClass,
	getDueDateStatus,
	truncateText,
	highlightText,
	formatNumber,
	formatPercent,
} from "./lib/formatters";

// Calculations
export {
	calculateStats,
	calculateConversionMetrics,
	calculateAvgDaysInStage,
	calculateActivityMetrics,
	calculatePriorityScore,
	sortByPriority,
} from "./lib/calculations";

// Filters
export {
	filterCompanies,
	sortCompanies,
	groupByStage,
	groupByDueDate,
} from "./lib/filters";
