// ESOP Partner CRM Constants

export const ALL_STATES = [
  'Nationwide', 'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA',
  'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI',
  'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND',
  'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA',
  'WA', 'WV', 'WI', 'WY'
] as const;

export const TYPE_COLORS: Record<string, { bg: string; text: string }> = {
  'Lender': { bg: '#E6F1FB', text: '#0C447C' },
  'Attorney': { bg: '#EEEDFE', text: '#3C3489' },
  'CPA': { bg: '#E1F5EE', text: '#085041' },
  'Administrator': { bg: '#FAEEDA', text: '#633806' },
  'Appraiser': { bg: '#FAECE7', text: '#712B13' },
  'Trustee': { bg: '#F0EDF8', text: '#5B3FA0' },
  'Financial Advisor': { bg: '#E1F5EE', text: '#085041' },
  'Other': { bg: '#F1EFE8', text: '#444441' },
};

export const STAGE_META: Record<string, { label: string; score: number }> = {
  prospect: { label: 'Prospect', score: 10 },
  introduced: { label: 'Introduced', score: 35 },
  active: { label: 'Active partner', score: 65 },
  preferred: { label: 'Preferred partner', score: 90 },
  dormant: { label: 'Dormant', score: 5 },
};

export const NUDGE_DAYS: Record<string, number> = {
  prospect: 30,
  introduced: 21,
  active: 14,
  preferred: 14,
  dormant: 90,
};

export const STAGE_ORDER = ['prospect', 'introduced', 'active', 'preferred', 'dormant'] as const;

export const NUDGE_ACTIONS: Record<string, string> = {
  prospect: 'Send intro email',
  introduced: 'Schedule discovery call',
  active: 'Check in on pipeline',
  preferred: 'Quarterly relationship call',
  dormant: 'Re-engagement outreach',
};

export const ACTIVITY_COLORS: Record<string, string> = {
  deal: '#1D9E75',
  call: '#185FA5',
  email: '#5B3FA8',
  doc: '#854F0B',
  referral: '#B8860B',
  event: '#993C1D',
};

export const JOURNEY_STEPS: Record<string, Array<{ id: string; name: string; desc: string; docLabel?: string }>> = {
  'Lender': [
    { id: 'research', name: 'Research & qualify', desc: 'Confirm SBA 7(a) ESOP appetite, geography, loan size' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send firm intro + ESOP overview one-pager', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: '30-min call — volume, deal size, SBA experience' },
    { id: 'pkg-sent', name: 'Lender package sent', desc: 'Send sample ESOP deal package and term sheet', docLabel: 'Lender Package' },
    { id: 'mtg', name: 'In-person / Zoom meeting', desc: 'Present firm capabilities and deal flow pipeline' },
    { id: 'nda', name: 'NDA executed', desc: 'Mutual NDA signed before sharing deal specifics', docLabel: 'NDA' },
    { id: 'pref-agr', name: 'Preferred lender agreement', desc: 'Execute preferred lender MOU or referral agreement', docLabel: 'Preferred Agreement' },
    { id: 'first-deal', name: 'First deal submitted', desc: 'Submit first live ESOP credit memo' },
  ],
  'Attorney': [
    { id: 'research', name: 'Research & qualify', desc: 'Confirm ESOP transaction experience and deal types' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send firm overview and ESOP practice description', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: 'Discuss ESOP deal experience, plan doc capabilities' },
    { id: 'capability', name: 'Capability statement sent', desc: 'Share transaction process and advisor roles', docLabel: 'Capability Statement' },
    { id: 'mtg', name: 'Working meeting', desc: 'Review sample plan document and process together' },
    { id: 'nda', name: 'NDA / conflict check', desc: 'Mutual NDA executed; conflict check completed', docLabel: 'NDA' },
    { id: 'engagement', name: 'Engagement letter template', desc: 'Agree on standard engagement letter terms', docLabel: 'Engagement Letter Template' },
    { id: 'first-deal', name: 'First deal referred', desc: 'Refer or co-counsel first ESOP transaction' },
  ],
  'CPA': [
    { id: 'research', name: 'Research & qualify', desc: 'Confirm ESOP tax experience — §1042, S-corp conversions' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send intro with ESOP tax planning overview', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: 'Discuss §1042 volume, seller tax planning work' },
    { id: 'whitepaper', name: 'Tax whitepaper sent', desc: 'Share ESOP tax benefits white paper', docLabel: 'Tax Whitepaper' },
    { id: 'mtg', name: 'Strategy meeting', desc: 'Walk through seller economics model together' },
    { id: 'nda', name: 'NDA executed', desc: 'Mutual NDA signed', docLabel: 'NDA' },
    { id: 'referral-agr', name: 'Referral agreement', desc: 'Execute mutual referral / co-advisory agreement', docLabel: 'Referral Agreement' },
    { id: 'first-deal', name: 'First deal engaged', desc: 'CPA engaged on live ESOP transaction' },
  ],
  'Administrator': [
    { id: 'research', name: 'Research & qualify', desc: 'Confirm TPA ESOP admin capabilities — leveraged, S-ESOP' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send intro and deal flow overview', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: 'Review admin services, fee structure, responsiveness' },
    { id: 'fee-schedule', name: 'Fee schedule received', desc: 'Obtain and review standard TPA fee schedule', docLabel: 'Fee Schedule' },
    { id: 'mtg', name: 'Capability review', desc: 'Walk through first-year allocation and admin process' },
    { id: 'nda', name: 'NDA executed', desc: 'Mutual NDA signed', docLabel: 'NDA' },
    { id: 'panel', name: 'Added to preferred panel', desc: 'Add to preferred TPA panel and referral list' },
    { id: 'first-deal', name: 'First deal engaged', desc: 'TPA engaged on live ESOP deal' },
  ],
  'Appraiser': [
    { id: 'research', name: 'Research & qualify', desc: 'Confirm ESOP valuation credentials — NACVA, ASA' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send intro and valuation process overview', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: 'Discuss methodology, turnaround time, fees' },
    { id: 'sample', name: 'Sample report received', desc: 'Review sample fairness opinion / valuation report', docLabel: 'Sample Report' },
    { id: 'mtg', name: 'Technical review', desc: 'Walk through ESOP valuation methodology together' },
    { id: 'nda', name: 'NDA executed', desc: 'Mutual NDA signed', docLabel: 'NDA' },
    { id: 'panel', name: 'Added to preferred panel', desc: 'Add to preferred appraiser panel' },
    { id: 'first-deal', name: 'First engagement', desc: 'Appraiser engaged on live ESOP transaction' },
  ],
  'Trustee': [
    { id: 'research', name: 'Research & qualify', desc: 'Confirm independent trustee experience, bonding, E&O' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send firm overview and trustee process doc', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: 'Discuss independence policy, fee structure, geography' },
    { id: 'process-doc', name: 'Process document exchanged', desc: 'Share trustee engagement process and timeline', docLabel: 'Process Document' },
    { id: 'mtg', name: 'Relationship meeting', desc: 'Meet key personnel; review transaction experience' },
    { id: 'nda', name: 'NDA / conflict policy', desc: 'Mutual NDA and conflict of interest policy reviewed', docLabel: 'NDA' },
    { id: 'panel', name: 'Added to preferred panel', desc: 'Add to preferred trustee panel' },
    { id: 'first-deal', name: 'First engagement', desc: 'Trustee engaged on live ESOP transaction' },
  ],
  'default': [
    { id: 'research', name: 'Research & qualify', desc: 'Initial research and qualification' },
    { id: 'intro-email', name: 'Introduction email', desc: 'Send firm introduction email', docLabel: 'Introduction Email' },
    { id: 'intro-call', name: 'Discovery call', desc: 'Introduction call to explore partnership fit' },
    { id: 'materials', name: 'Materials sent', desc: 'Share firm materials and capabilities', docLabel: 'Firm Materials' },
    { id: 'mtg', name: 'In-person / Zoom meeting', desc: 'Formal capability presentation' },
    { id: 'nda', name: 'NDA executed', desc: 'Mutual NDA signed', docLabel: 'NDA' },
    { id: 'agreement', name: 'Partnership agreement', desc: 'Execute partnership or referral agreement', docLabel: 'Partnership Agreement' },
    { id: 'first-deal', name: 'First deal together', desc: 'First live transaction collaboration' },
  ],
};

export const DEFAULT_CONTACTS = [
  {
    id: 1,
    first: 'Sarah',
    last: 'Mitchell',
    firm: 'Heartland SBA Lending',
    type: 'Lender' as const,
    email: 'smitchell@heartlandsba.com',
    phone: '(312) 555-0182',
    states: ['IL', 'WI', 'MN', 'IA'],
    stage: 'preferred' as const,
    lastContact: '2025-03-01',
    notes: 'Lead SBA 7(a) lender. Fast closings, Midwest focus.',
    preferred: true,
    journey: {
      research: { status: 'done', date: '2024-06-01' },
      'intro-email': { status: 'done', date: '2024-06-05', docSent: true },
      'intro-call': { status: 'done', date: '2024-06-15' },
      'pkg-sent': { status: 'done', date: '2024-07-01', docSent: true },
      mtg: { status: 'done', date: '2024-07-20' },
      nda: { status: 'done', date: '2024-08-01', docSent: true },
      'pref-agr': { status: 'done', date: '2024-09-01', docSent: true },
      'first-deal': { status: 'done', date: '2024-10-15' },
    },
    notes_log: [
      { id: 'n1', text: 'Closed Meridian Manufacturing — $8.4M 7(a). Excellent turnaround.', ts: '2025-03-01T14:22:00' },
      { id: 'n2', text: 'Prefers email. Responds within 4 hours.', ts: '2024-09-15T09:10:00' },
    ],
    activities: [
      { id: 'a1', text: 'Closed Meridian Manufacturing — $8.4M 7(a)', date: '2025-03-01', time: '14:22', type: 'deal' as const },
      { id: 'a2', text: 'Quarterly check-in call', date: '2025-01-14', time: '10:00', type: 'call' as const },
      { id: 'a3', text: 'Preferred lender agreement executed', date: '2024-09-01', time: '16:00', type: 'doc' as const },
    ],
  },
  {
    id: 2,
    first: 'James',
    last: 'Okafor',
    firm: 'Okafor & Reeves LLP',
    type: 'Attorney' as const,
    email: 'jokafor@okaforlaw.com',
    phone: '(614) 555-0233',
    states: ['OH', 'PA', 'MI'],
    stage: 'active' as const,
    lastContact: '2025-02-20',
    notes: 'ESOP transaction counsel. Strong on plan docs.',
    preferred: false,
    journey: {
      research: { status: 'done', date: '2024-08-01' },
      'intro-email': { status: 'done', date: '2024-08-10', docSent: true },
      'intro-call': { status: 'done', date: '2024-08-22' },
      capability: { status: 'done', date: '2024-09-05', docSent: true },
      mtg: { status: 'done', date: '2024-10-01' },
      nda: { status: 'current', date: null },
      engagement: { status: 'pending' },
      'first-deal': { status: 'pending' },
    },
    notes_log: [
      { id: 'n1', text: 'Strong on SBA plan docs. Slightly slower on trustee coordination.', ts: '2025-02-20T11:30:00' },
    ],
    activities: [
      { id: 'a1', text: 'Draft trust agreement sent for review', date: '2025-02-20', time: '11:30', type: 'doc' as const },
      { id: 'a2', text: 'Intro call — discussed deal flow', date: '2024-12-10', time: '09:00', type: 'call' as const },
    ],
  },
  {
    id: 3,
    first: 'Linda',
    last: 'Pham',
    firm: 'Pham Tax Group',
    type: 'CPA' as const,
    email: 'lpham@phamtax.com',
    phone: '(415) 555-0094',
    states: ['CA', 'NV', 'OR'],
    stage: 'preferred' as const,
    lastContact: '2025-03-05',
    notes: '§1042 specialist. QRP strategy and seller tax planning.',
    preferred: true,
    journey: {
      research: { status: 'done', date: '2024-01-10' },
      'intro-email': { status: 'done', date: '2024-01-15', docSent: true },
      'intro-call': { status: 'done', date: '2024-01-28' },
      whitepaper: { status: 'done', date: '2024-02-10', docSent: true },
      mtg: { status: 'done', date: '2024-03-01' },
      nda: { status: 'done', date: '2024-03-15', docSent: true },
      'referral-agr': { status: 'done', date: '2024-04-01', docSent: true },
      'first-deal': { status: 'done', date: '2024-05-20' },
    },
    notes_log: [
      { id: 'n1', text: 'Co-presented ESOP Tax Update webinar. High credibility.', ts: '2025-01-22T15:00:00' },
    ],
    activities: [
      { id: 'a1', text: '§1042 QRP consult — Pacific Coast Plastics', date: '2025-03-05', time: '13:00', type: 'deal' as const },
      { id: 'a2', text: 'Webinar co-presenter — ESOP Tax Update', date: '2025-01-22', time: '15:00', type: 'event' as const },
    ],
  },
  {
    id: 4,
    first: 'David',
    last: 'Yuen',
    firm: 'Pacific Coast SBA',
    type: 'Lender' as const,
    email: 'dyuen@pcsba.com',
    phone: '(213) 555-0641',
    states: ['CA', 'AZ', 'NV'],
    stage: 'introduced' as const,
    lastContact: '2024-12-18',
    notes: 'Met at NCEO conference. West Coast pipeline interest.',
    preferred: false,
    journey: {
      research: { status: 'done', date: '2024-11-10' },
      'intro-email': { status: 'done', date: '2024-11-15', docSent: true },
      'intro-call': { status: 'done', date: '2024-12-18' },
      'pkg-sent': { status: 'current', date: null },
      mtg: { status: 'pending' },
      nda: { status: 'pending' },
      'pref-agr': { status: 'pending' },
      'first-deal': { status: 'pending' },
    },
    notes_log: [
      { id: 'n1', text: 'Strong interest in CA deals. Send lender package before year end.', ts: '2024-11-14T16:30:00' },
    ],
    activities: [
      { id: 'a1', text: 'Follow-up email after NCEO conference', date: '2024-12-18', time: '09:00', type: 'email' as const },
      { id: 'a2', text: 'Met at NCEO Annual Conference', date: '2024-11-14', time: '16:30', type: 'event' as const },
    ],
  },
  {
    id: 5,
    first: 'Angela',
    last: 'Torres',
    firm: 'Torres & Ruiz PLLC',
    type: 'Attorney' as const,
    email: 'atorres@torresruiz.com',
    phone: '(713) 555-0752',
    states: ['TX', 'OK', 'NM'],
    stage: 'prospect' as const,
    lastContact: '2024-10-30',
    notes: 'Referred by Linda Pham. Texas ESOP market.',
    preferred: false,
    journey: {
      research: { status: 'done', date: '2024-10-28' },
      'intro-email': { status: 'current', date: null },
      capability: { status: 'pending' },
      mtg: { status: 'pending' },
      nda: { status: 'pending' },
      engagement: { status: 'pending' },
      'first-deal': { status: 'pending' },
    },
    notes_log: [
      { id: 'n1', text: 'Inbound referral from Linda Pham. Schedule intro call ASAP.', ts: '2024-10-30T14:00:00' },
    ],
    activities: [
      { id: 'a1', text: 'Inbound referral from Linda Pham', date: '2024-10-30', time: '14:00', type: 'referral' as const },
    ],
  },
];
