// Re-export shared logic layer
export type {
  LenderQAInputs,
  DealHeader,
  QAItem,
  QAStatus,
  QAPriority,
  QACategory,
  QASource,
  QAFilter,
  LoanType,
  DealStage,
  ValidationError,
  MetricsData,
  CategoryProgress,
} from "@forhemit/shared/features/lender-qa-tracker";

export {
  CATEGORIES,
  LOAN_TYPE_OPTIONS,
  DEAL_STAGE_OPTIONS,
  QA_STATUS_OPTIONS,
  QA_PRIORITY_OPTIONS,
  QA_SOURCE_OPTIONS,
  FILTER_OPTIONS,
  SBA_LOAN_LIMITS,
  DEFAULT_DEAL_HEADER,
  DEFAULT_QA_ITEM,
  DEFAULT_INPUTS,
  STEPS,
  ESOP_TEMPLATE_ITEMS,
  useLenderQAForm,
  validateEmail,
  validateDealId,
  validatePositiveNumber,
  validatePhone,
  formatPhone,
  validateDates,
  checkLoanLimit,
  validateDealHeader,
  validateQAItem,
  isOverdue,
  isNearDue,
  calculateMetrics,
  calculateCategoryProgress,
  generateItemId,
  formatDate,
  formatCurrency,
  getLoanTypeLabel,
  filterItems,
  groupItemsByCategory,
} from "@forhemit/shared/features/lender-qa-tracker";
