/**
 * Template Rules — Automation trigger metadata for all 169 manifest entries.
 *
 * Each rule maps a manifest entry to a trigger type, gate reference,
 * fee milestone, and auto-send flag. Used by the seed mutation to populate
 * the stageRequirements table with automation metadata.
 */

export type TriggerType =
  | "MANUAL"
  | "ON_STAGE_ENTRY"
  | "ON_GATE_PASSED"
  | "DAYS_FROM_STAGE"
  | "DAYS_FROM_EVENT"
  | "DAYS_FROM_GATE"
  | "DAYS_BEFORE_CLOSING"
  | "ON_CLOSING"
  | "ON_POST_CLOSE"
  | "RECURRING";

export interface TemplateRule {
  manifestId: string;
  title: string;
  trigger: TriggerType;
  triggerGate?: string;
  daysOffset?: number;
  recurringRule?: string;
  feeMilestone?: string;
  autoSend: boolean;
  notes: string;
}

export const templateRules: TemplateRule[] = [
  { manifestId: "external/01-first-touch/broker-intro-packet", title: "Broker introduction packet", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/cold-outreach-broker", title: "Cold outreach email — broker (first touch)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/cold-outreach-cpa", title: "Cold outreach email — CPA (first touch)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/cold-outreach-seller", title: "Cold outreach email — seller (owner-direct)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/referral-acknowledgment", title: "Referral acknowledgment (when someone sends a lead)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/linkedin-followup", title: "LinkedIn connection follow-up (post-accept)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/thank-you-ecosystem", title: "Thank-you email (post-call, non-deal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/exit-strategy-benchmark", title: "Exit strategy benchmark (ESOP vs PE vs strategic vs succession)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/01-first-touch/employee-communications-plan", title: "Employee communications plan (pre- and post-close)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/nda-mutual", title: "NDA (mutual — deal team)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/broker-nda", title: "Broker NDA / confidentiality agreement", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/deal-screener-response", title: "Deal screener email (broker → Forhemit)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/pre-flight-checklist", title: "Pre-flight checklist (signed by seller + Forhemit)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/pre-flight-cover-letter", title: "Pre-flight checklist cover letter (to seller)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/no-fit-decline-seller", title: "No-fit decline email (seller)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/no-fit-decline-broker", title: "No-fit decline email (broker)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/conditional-go-letter", title: "Conditional go letter (pre-flight)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/nda-receipt-confirmation", title: "NDA Receipt Confirmation", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/03-engagement/engagement-letter", title: "Engagement letter (seller-facing)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters engagement stage" },
  { manifestId: "external/03-engagement/engagement-letter-cover", title: "Engagement letter cover email (to seller)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters engagement stage" },
  { manifestId: "external/03-engagement/loi-template", title: "Letter of intent (LOI) template", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters engagement stage" },
  { manifestId: "external/03-engagement/loi-transmittal", title: "LOI transmittal letter", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters engagement stage" },
  { manifestId: "external/03-engagement/broker-deal-acceptance", title: "Broker deal acceptance email", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/referral-fee-agreement", title: "Referral fee agreement", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/advisor-intro-trustee", title: "Advisor introduction email (trustee)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/advisor-intro-counsel", title: "Advisor introduction email (ERISA counsel)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/lender-intro-package", title: "SBA lender introduction package cover email", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/seller-onboarding-day1", title: "Seller onboarding email — Day 1: Welcome + what to expect", trigger: "DAYS_FROM_EVENT", daysOffset: 0, autoSend: false, notes: "Day 1 — welcome + what to expect" },
  { manifestId: "external/03-engagement/seller-onboarding-day2", title: "Seller onboarding email — Day 2: Document request list", trigger: "DAYS_FROM_EVENT", daysOffset: 1, autoSend: false, notes: "Day 2 — document portal walkthrough" },
  { manifestId: "external/03-engagement/seller-onboarding-day3", title: "Seller onboarding email — Day 3: Calendar link", trigger: "DAYS_FROM_EVENT", daysOffset: 2, autoSend: false, notes: "Day 3 — financial overview request" },
  { manifestId: "external/03-engagement/seller-onboarding-day4", title: "Seller onboarding email — Day 4: Team introduction", trigger: "DAYS_FROM_EVENT", daysOffset: 3, autoSend: false, notes: "Day 4 — team introduction" },
  { manifestId: "external/03-engagement/seller-onboarding-day5", title: "Seller onboarding email — Day 5: First check-in", trigger: "DAYS_FROM_EVENT", daysOffset: 4, autoSend: false, notes: "Day 5 — first check-in" },
  { manifestId: "external/03-engagement/trustee-retainer", title: "Trustee retainer agreement (company → trustee)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/erisa-counsel-retainer", title: "ERISA counsel retainer agreement (company → counsel)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/trustee-rfp", title: "Trustee RFP (formal request for proposal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/cpa-engagement-confirmation", title: "CPA engagement confirmation", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/cpa-tax-coordination-update", title: "CPA tax coordination update", trigger: "RECURRING", recurringRule: "during-diligence", autoSend: false, notes: "Recurring during-diligence" },
  { manifestId: "internal/04-diligence/trustee-diligence-log", title: "Trustee diligence log", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/counsel-legal-status-update", title: "Counsel legal status update request", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/gate1-passage-confirmation", title: "Gate 1 passage confirmation (internal + seller)", trigger: "ON_GATE_PASSED", triggerGate: "gate1", autoSend: false, notes: "Gate 1 passage confirmation to seller + advisor team" },
  { manifestId: "external/04-diligence/gate2-passage-confirmation", title: "Gate 2 passage confirmation (internal + seller)", trigger: "ON_GATE_PASSED", triggerGate: "gate2", autoSend: false, notes: "Gate 2 passage confirmation" },
  { manifestId: "external/04-diligence/gate3-passage-confirmation", title: "Gate 3 passage confirmation (internal + seller)", trigger: "ON_GATE_PASSED", triggerGate: "gate3", autoSend: false, notes: "Gate 3 passage confirmation" },
  { manifestId: "external/04-diligence/gate-failure-notice", title: "Gate failure / extension notice (seller)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/document-request-followup", title: "Document request follow-up (seller)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/weekly-status-seller", title: "Weekly deal status update (seller-facing)", trigger: "RECURRING", recurringRule: "weekly", autoSend: false, notes: "Recurring weekly" },
  { manifestId: "external/04-diligence/weekly-status-broker", title: "Weekly deal status update (broker-facing)", trigger: "RECURRING", recurringRule: "weekly", autoSend: false, notes: "Recurring weekly" },
  { manifestId: "external/04-diligence/qofe-coordination-request", title: "QofE coordination request (to seller's CPA)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/lender-update", title: "Lender update email (during underwriting)", trigger: "RECURRING", recurringRule: "weekly", autoSend: false, notes: "Recurring weekly" },
  { manifestId: "external/04-diligence/trustee-update", title: "Trustee update memo (during appraisal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/broker-pipeline-status", title: "Broker pipeline status update template", trigger: "RECURRING", recurringRule: "weekly", autoSend: false, notes: "Recurring weekly" },
  { manifestId: "external/04-diligence/turnover-cost-calculator", title: "Turnover cost calculator — key person risk assessment", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/04-diligence/fairness-opinion-package", title: "Fairness opinion package (trustee's financial advisor)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/05-closing/closing-date-confirmation", title: "Closing date confirmation (seller)", trigger: "DAYS_BEFORE_CLOSING", daysOffset: 10, autoSend: false, notes: "Closing date confirmation — 10 days before" },
  { manifestId: "external/05-closing/closing-congratulations", title: "Closing congratulations letter (seller)", trigger: "ON_CLOSING", autoSend: false, notes: "Sent same day as close" },
  { manifestId: "external/05-closing/broker-commission-confirmation", title: "Broker commission confirmation (closing)", trigger: "ON_CLOSING", autoSend: false, notes: "Broker commission at closing" },
  { manifestId: "external/05-closing/employee-announcement", title: "Employee announcement template (Day 1)", trigger: "ON_CLOSING", autoSend: false, notes: "Employee announcement on closing day" },
  { manifestId: "external/05-closing/closing-package-tax-filing", title: "Closing tax package (for seller's CPA)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/05-closing/press-release", title: "Press release template (optional)", trigger: "ON_CLOSING", autoSend: false, notes: "Press release at closing" },
  { manifestId: "external/05-closing/esop-town-hall-agenda", title: "First Day as ESOP town hall agenda + employee FAQ", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/05-closing/trustee-welcome-letter", title: "Trustee welcome letter to employees", trigger: "ON_CLOSING", autoSend: false, notes: "Trustee welcome to company at closing" },
  { manifestId: "external/05-closing/manager-briefing-talking-points", title: "Manager briefing talking points", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/05-closing/welcome-to-your-esop-booklet", title: "Welcome to Your ESOP booklet", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/06-post-close/coop-kickoff-letter", title: "COOP kickoff letter (to operating company)", trigger: "ON_POST_CLOSE", autoSend: false, notes: "COOP stewardship kickoff" },
  { manifestId: "external/06-post-close/coop-stewardship-agreement", title: "COOP stewardship agreement", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/06-post-close/monthly-checkin-agenda", title: "Monthly COOP check-in agenda", trigger: "RECURRING", recurringRule: "monthly", autoSend: false, notes: "Recurring monthly" },
  { manifestId: "external/06-post-close/quarterly-status-report", title: "COOP track status report (quarterly)", trigger: "RECURRING", recurringRule: "quarterly", autoSend: false, notes: "Recurring quarterly" },
  { manifestId: "external/06-post-close/refinance-trigger", title: "Refinance trigger notification (Month 14–18)", trigger: "ON_POST_CLOSE", daysOffset: 420, autoSend: false, notes: "Refinance trigger letter ~14 months post-close" },
  { manifestId: "external/06-post-close/seller-note-retirement", title: "Seller note retirement confirmation", trigger: "ON_POST_CLOSE", autoSend: false, notes: "Seller note retirement notice" },
  { manifestId: "external/06-post-close/coop-completion-letter", title: "COOP completion letter (end of stewardship)", trigger: "ON_POST_CLOSE", autoSend: false, notes: "COOP completion letter" },
  { manifestId: "external/06-post-close/anniversary-note", title: "Employee ownership anniversary note (Year 1)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/06-post-close/case-study-request", title: "Case study request (post-close)", trigger: "ON_POST_CLOSE", autoSend: false, notes: "Case study request post-close" },
  { manifestId: "external/06-post-close/repurchase-obligation-study", title: "Repurchase obligation study", trigger: "ON_POST_CLOSE", autoSend: false, notes: "Repurchase obligation study" },
  { manifestId: "external/06-post-close/distribution-policy", title: "ESOP distribution policy", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/06-post-close/esop-satisfaction-survey", title: "ESOP satisfaction survey (annual, employees)", trigger: "RECURRING", recurringRule: "annually", autoSend: false, notes: "Recurring annually" },
  { manifestId: "external/06-post-close/cpa-post-close-tax-reminder", title: "CPA post-close tax reminder", trigger: "RECURRING", recurringRule: "annually", autoSend: false, notes: "Recurring annually" },
  { manifestId: "external/06-post-close/broker-referral-nurture", title: "Broker referral nurture package", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/06-post-close/seller-exit-interview", title: "Seller exit interview", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/06-post-close/trustee-annual-review-agenda", title: "Trustee annual review agenda", trigger: "RECURRING", recurringRule: "annually", autoSend: false, notes: "Recurring annually" },
  { manifestId: "external/06-post-close/counsel-annual-compliance-reminder", title: "Counsel annual compliance reminder", trigger: "RECURRING", recurringRule: "annually", autoSend: false, notes: "Recurring annually" },
  { manifestId: "external/06-post-close/annual-benefit-statement-cover", title: "Annual benefit statement cover letter", trigger: "RECURRING", recurringRule: "annually", autoSend: false, notes: "Recurring annually" },
  { manifestId: "external/06-post-close/ownership-culture-workshop-guide", title: "Ownership culture workshop guide", trigger: "RECURRING", recurringRule: "quarterly", autoSend: false, notes: "Recurring quarterly" },
  { manifestId: "internal/01-first-touch/inbound-auto-response", title: "Inbound inquiry auto-response (email)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/01-first-touch/voicemail-script", title: "Voicemail script (Retell AI / live)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/01-first-touch/conference-followup", title: "Conference / event follow-up email", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/01-first-touch/email-signature-standard", title: "Email signature standard (all staff)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/01-first-touch/ooo-coverage-message", title: "Out-of-office / coverage message standard", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/01-first-touch/meeting-confirmation", title: "Meeting confirmation email template", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/01-first-touch/no-show-followup", title: "No-show / reschedule follow-up", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/01-first-touch/confidentiality-reminder", title: "Confidentiality reminder (recurring, internal)", trigger: "RECURRING", recurringRule: "quarterly", autoSend: false, notes: "Recurring quarterly" },
  { manifestId: "internal/01-first-touch/style-guide", title: "Style guide and writing standards one-pager", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/02-qualification/deal-intake-form", title: "Deal intake form", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/02-qualification/classification-intake", title: "Classification intake flow", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/02-qualification/deal-intake-confirmation", title: "Deal intake confirmation (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/02-qualification/new-deal-announcement", title: "New deal announcement (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/02-qualification/pre-flight-checklist-internal", title: "Pre-flight checklist (internal version)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "internal/03-engagement/deal-team-kickoff", title: "Deal team kick-off memo (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/03-engagement/vendor-onboarding-checklist", title: "Vendor / advisor onboarding checklist", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/03-engagement/conflict-of-interest-log", title: "Conflict of interest log", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/03-engagement/wire-instructions", title: "Wire instruction sheet (standard)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/03-engagement/llc-to-corp-checklist", title: "LLC-to-C-corp conversion checklist", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/gate-tracking-dashboard", title: "Gate tracking dashboard", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/weekly-internal-review", title: "Weekly internal deal review agenda", trigger: "RECURRING", recurringRule: "weekly", autoSend: false, notes: "Recurring weekly" },
  { manifestId: "internal/04-diligence/fee-collection-tracker", title: "Fee collection tracker", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/invoice-template", title: "Invoice template (Forhemit → operating company)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/qofe-findings-memo", title: "QofE findings memo (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/eidl-lien-tracker", title: "EIDL lien resolution tracker", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/eidl-lien-status-update", title: "EIDL lien status update (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/05-closing/gate4-legal-clearance", title: "Gate 4 / legal clearance memo (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/05-closing/closing-checklist", title: "Closing checklist (deal team)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/05-closing/deal-close-announcement", title: "Deal close announcement (internal)", trigger: "ON_CLOSING", autoSend: false, notes: "Deal close announcement" },
  { manifestId: "internal/05-closing/employee-communication-strategy-checklist", title: "Employee communication strategy checklist (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/06-post-close/lessons-learned-memo", title: "Lessons learned memo (post-close, internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/06-post-close/coop-intake-forms", title: "COOP intake forms (Track 1 People, Track 2 Systems)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/06-post-close/coop-delivery-tracker", title: "COOP delivery tracker (V1.0 – V4.0)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/06-post-close/employee-feedback-tracker", title: "Employee feedback tracker (internal)", trigger: "RECURRING", recurringRule: "quarterly", autoSend: false, notes: "Recurring quarterly" },
  { manifestId: "external/02-qualification/transaction-cost-disclosure", title: "Transaction cost disclosure", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/offer-summary", title: "Offer summary (V3)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/honest-review", title: "Honest Review document", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/120-day-calendar", title: "120-day calendar", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "external/02-qualification/seller-faq", title: "Seller FAQ / plain-language guide", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/1042-explainer", title: "§1042 rollover explainer (seller's CPA version)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/tax-impact-summary", title: "Tax impact summary (ESOP vs third-party sale)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/net-proceeds-calculator", title: "Net proceeds calculator (interactive)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/broker-screener", title: "Broker screener / qualification form", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/two-track-cost-analysis", title: "Two-track cost analysis (full doc)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/esop-cost-reference", title: "ESOP cost reference card (3-way framework)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/seller-document-request", title: "Seller document request list", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/esop-ecosystem-outreach", title: "ESOP ecosystem outreach playbook", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/board-resolution-package", title: "Board resolution package", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/roles-independence-matrix", title: "Roles & independence matrix", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/dream-team-roster", title: "Dream team roster + mini-RFP", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/erisa-counsel-rfp", title: "ERISA counsel RFP / conflict check request", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/trustee-engagement-memo", title: "Trustee engagement memo (introduction letter)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/valuation-firm-briefing", title: "Valuation firm briefing memo", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/sba-lender-outreach", title: "SBA lender outreach brief (one-pager)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/sba-intake-form", title: "SBA intake form", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/lender-interview-questions", title: "Lender qualification interview questions", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/lender-scoring-rubric", title: "Lender scoring rubric", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/lender-qa-tracker", title: "Lender Q&A tracker", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/repayment-model", title: "Repayment / amortization model", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/capital-stack-summary", title: "Capital stack summary (lender package cover)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/intercreditor-agreement", title: "Intercreditor agreement template", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/esop-head-to-head", title: "ESOP head-to-head comparison", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/esop-term-sheet", title: "ESOP term sheet", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/intro-letter-generator", title: "Intro letter generator", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/02-qualification/esop-qualification-prompt", title: "ESOP qualification prompt", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "external/03-engagement/ebitda-confirmation-letter", title: "EBITDA Confirmation Letter", trigger: "DAYS_FROM_EVENT", daysOffset: 0, feeMilestone: "retainer", autoSend: false, notes: "Formalizes QofE EBITDA and tier before engagement signing" },
  { manifestId: "external/04-diligence/pre-close-board-resolution", title: "Pre-Close Board Resolution — Fee Authorization", trigger: "DAYS_FROM_GATE", triggerGate: "gate3", daysOffset: 7, autoSend: false, notes: "Board authorizes Success Balance. ~7 days after Gate 3." },
  { manifestId: "external/04-diligence/validation-fee-invoice", title: "Validation Fee Invoice", trigger: "ON_GATE_PASSED", triggerGate: "gate1", feeMilestone: "validation", autoSend: true, notes: "Invoice at Gate 1 clearance. Milestone 2/4, Net 7." },
  { manifestId: "external/04-diligence/commitment-fee-invoice", title: "Commitment Fee Invoice", trigger: "ON_GATE_PASSED", triggerGate: "gate2", feeMilestone: "commitment", autoSend: true, notes: "Invoice at Gate 2 clearance. Milestone 3/4, Net 7." },
  { manifestId: "external/05-closing/success-balance-invoice", title: "Success Balance Invoice", trigger: "DAYS_BEFORE_CLOSING", daysOffset: 5, feeMilestone: "success", autoSend: true, notes: "Invoice 5 days before closing. Milestone 4/4." },
  { manifestId: "external/06-post-close/stewardship-payment-schedule", title: "Post-Close Stewardship Payment Schedule", trigger: "ON_POST_CLOSE", feeMilestone: "stewardship", autoSend: false, notes: "Tranche schedule summary sent post-close." },
  { manifestId: "external/06-post-close/stewardship-fee-tranche-invoice", title: "Stewardship Fee Tranche Invoice", trigger: "RECURRING", recurringRule: "quarterly", feeMilestone: "stewardship", autoSend: true, notes: "Quarterly stewardship fee invoice." },
  { manifestId: "external/06-post-close/stewardship-agreement-summary", title: "Transition Stewardship Agreement Summary", trigger: "ON_POST_CLOSE", autoSend: false, notes: "Plain-language summary for incoming CEO." },
  { manifestId: "external/06-post-close/officer-onboarding-fee-disclosure", title: "Officer Onboarding Fee Disclosure Package", trigger: "ON_POST_CLOSE", autoSend: false, notes: "Fee disclosure package for new CEO." },
  { manifestId: "internal/04-diligence/fee-collection-checklist", title: "Fee Collection Checklist", trigger: "ON_STAGE_ENTRY", autoSend: true, notes: "Internal fee collection checklist. INT-FEE-001." },
  { manifestId: "external/02-qualification/broker-screener-form", title: "Broker screener / qualification form", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/02-qualification/new-deal-alert", title: "New deal alert (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/02-qualification/pre-flight-checklist-sent", title: "Pre-flight checklist sent confirmation (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Fires when deal enters qualification stage" },
  { manifestId: "internal/03-engagement/engagement-signed-alert", title: "Engagement signed alert (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/03-engagement/loi-signed-alert", title: "LOI signed alert (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/03-engagement/team-assembly-kickoff", title: "Team assembly & kickoff (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/04-diligence/deal-economics-model", title: "Deal economics model (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/gate4-legal-clearance", title: "Gate 4 / legal clearance memo (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/04-diligence/lender-qa-tracker", title: "Lender Q&A tracker (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/04-diligence/repayment-amortization-model", title: "Repayment & amortization model (internal)", trigger: "MANUAL", autoSend: false, notes: "Manual: team generates in dashboard" },
  { manifestId: "internal/05-closing/closing-confirmation", title: "Closing confirmation (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/05-closing/wire-instructions", title: "Wire instructions (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
  { manifestId: "internal/06-post-close/stewardship-billing", title: "Stewardship billing tracker (internal)", trigger: "ON_STAGE_ENTRY", autoSend: false, notes: "Internal: fires on stage entry" },
];
